# Please modify these settings to ones that suit your needs
# Only change values after the colon (':')
MASTER_CONTROL: "controls/master_control.csv"
DUMP_FASTQ_FILES: "results/dump_fastq_input"
ROOTDIR: "results"

PERFORM_TRIM: True  # True or False
PERFORM_PREFETCH: False  # True or False

GENERATE_GENOME:
  GENOME_SAVE_DIR: "genome/star"
  GENOME_FASTA_FILE: "genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
  GTF_FILE: "genome/Homo_sapiens.GRCh38.104.gtf"
  # The "OVERHANG" value does not need to be modified
  OVERHANG: 99

# Please do not changes values below this line
ALIGN_READS:
  READ_COMMAND: "zcat"
  OUT_SAM_TYPE: "BAM SortedByCoordinate"
  OUT_SAM_UNMAPPED: "Within"
  OUT_SAM_ATTRIBUTES: "Standard"
  QUANT_MODE: "GeneCounts"
