# Modify these settings to reflect your paths
# Only change values after the colon (':')
MASTER_CONTROL: "controls/master_control.csv"
DUMP_FASTQ_FILES: "results/dump_fastq_input"
ROOTDIR: "results"

PERFORM_TRIM: True  # True or False
PERFORM_PREFETCH: True  # True or False


GENERATE_GENOME:
  # The full path where the genome generation data should be saved
  GENOME_SAVE_DIR: "genome/star"

  # The full input path of the genome fasta file and the GTF file
  GENOME_FASTA_FILE: "genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
  GTF_FILE: "genome/Homo_sapiens.GRCh38.104.gtf"
