# Modify these settings to reflect your paths
# Only change values after the colon (':')
MASTER_CONTROL: "controls/master_control.csv"  # csv with srr, rename, layout
ROOTDIR: "results" # redirect output root directory
DUMP_FASTQ_FILES: "results/dump_fastq_input" # downloaded fastq output file location
REF_FLAT_FILE: "genome/refFlat_GRCh38.105.txt"  # reflat file location built from gtf, for RNAseq metrics option
RRNA_INTERVAL_LIST: "genome/GRCh38.p5.rRNA.interval_list"  # rrna interval list file location, for RNAseq metrics
BED_FILE: "genome/Homo_sapiens.GRCh38.105.bed"  # reference bedfile build from GTF for RSEQC option

# Quality Control Options
PERFORM_TRIM: True  # True or False -- trim adapters prior to aligning
PERFORM_SCREEN: True # True or False -- screen against different genomes for contamination
PERFORM_GET_RNASEQ_METRICS: True # True or False -- get more information about RNA reads

# Additional options
PERFORM_PREFETCH: True  # True or False -- prefetch sra files before writing to fastq (recommended true)
PERFORM_GET_INSERT_SIZE: False # True or False -- insert sizes can also be used for fragment len calculation
PERFORM_GET_FRAGMENT_SIZE: False # True or False, required for zFPKM calculation

GENERATE_GENOME:
  # The full path where the genome generation data should be saved
  # This step will most likely not need to be performed
  # The genome is currently generated, do not change this unless necessary
  GENOME_SAVE_DIR: "genome/star"

  # The full input path of the genome fasta file and the GTF file
  # These files are currently present, and any user can read from these files
  # These values should not need to be changed unless necessary
  GENOME_FASTA_FILE: "genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
  GTF_FILE: "genome/Homo_sapiens.GRCh38.105.gtf"
