# Modify these settings to reflect your paths
# Only change values after the colon (':')
MASTER_CONTROL: "controls/master_control.csv"
DUMP_FASTQ_FILES: "results/dump_fastq_input"
ROOTDIR: "results"

PERFORM_TRIM: True  # True or False
PERFORM_PREFETCH: True  # True or False
PERFORM_SCREEN: True # True or False
PERFORM_GET_INSERT_SIZE: True # True or False, necessary for zFPKM calulation


GENERATE_GENOME:
  # The full path where the genome generation data should be saved
  # This step will most likely not need to be performed
  # The genome is currently generated, do not change this unless necessary
  GENOME_SAVE_DIR: "genome/star"

  # The full input path of the genome fasta file and the GTF file
  # These files are currently present, and any user can read from these files
  # These values should not need to be changed unless necessary
  GENOME_FASTA_FILE: "genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
  GTF_FILE: "genome/Homo_sapiens.GRCh38.105.gtf"
