# This file configures various settings for snakemake to execute jobs to a SLURM cluster.
# FROM: https://github.com/jdblischak/smk-simple-slurm

cluster:
  mkdir -p logs/{rule}/{resources.tissue_name} &&
  sbatch
  --job-name=smk-{rule}-{wildcards}
  --account=helikarlab
  --cpus-per-task={threads}
  --output=logs/{rule}/{resources.tissue_name}/{rule}-{wildcards}.out
  --mem={resources.mem_mb}
  --time={resources.runtime}
  --parsable

default-resources:
  - tissue_name=""
  - mem_mb=2048

# Job submittion
cores: 16  # Limit the maximum number of cores for grouped jobs
cluster-cancel: scancel
cluster-cancel-nargs: 50
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 5
latency-wait: 60
jobs: 100

# Other settings
printshellcmds: True
rerun-incomplete: True

# Changing these values may potentially result in groups not being submitted properly to SLURM,
# Thus causing an excess of jobs to be created and submitted to the cluster
groups:
  - preroundup=preroundupGroup_{tissue_name}
  - copy_gene_counts=copyGeneCountsGroup_{tissue_name}
  - copy_rnaseq_metrics=copyRnaSeqMetricsGroup_{tissue_name}
  - copy_insert_size=copyInsertSizeGroup_{tissue_name}
  - copy_fragment_size=copyFragmentSizeGroup_{tissue_name}
group-components:
  - preroundupGroup_{tissue_name}=20
  - copyGeneCountsGroup_{tissue_name}=20
  - copyRnaSeqMetricsGroup_{tissue_name}=20
  - copyInsertSizeGroup_{tissue_name}=20
  - copyFragmentSizeGroup_{tissue_name}=20

# Do not change these settings. This pipeline will fail to execute if they are changed
use-conda: True
conda-frontend: mamba
