# This file configures various settings for snakemake to execute jobs to a SLURM cluster.
# FROM: https://github.com/jdblischak/smk-simple-slurm

cluster-generic-submit-cmd:
  mkdir -p logs/{rule}/{resources.tissue_name} &&
  sbatch
  --job-name=smk-{rule}-{wildcards}
  --account=helikarlab
  --cpus-per-task={threads}
  --output=logs/{rule}/{resources.tissue_name}/{rule}-{wildcards}.out
  --mem={resources.mem_mb}
  --time={resources.runtime}
  --parsable

default-resources:
  - tissue_name=""
  - mem_mb=2048

# Job submittion
cores: 16  # Limit the maximum number of cores for grouped jobs
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 50
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 5
latency-wait: 60
jobs: 100

# Other settings
printshellcmds: True
rerun-incomplete: True
groups:
  - preroundup=preroundupGroup
  - copy_gene_counts=copyGeneCountsGroup
  - copy_rnaseq_metrics=copyRnaSeqMetricsGroup
  - copy_insert_size=copyInsertSizeGroup
  - copy_fragment_size=copyFragmentSizeGroup
group-components:
  - preroundupGroup=20
  - copyGeneCountsGroup=20
  - copyRnaSeqMetricsGroup=20
  - copyInsertSizeGroup=20
  - copyFragmentSizeGroup=20
  -
  # Do not change these settings. This pipeline will fail to execute if they are changed
software-deployment-method: conda
conda-frontend: mamba
