# This file configures various settings for snakemake to execute jobs to a SLURM cluster.
# FROM: https://github.com/jdblischak/smk-simple-slurm

cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --job-name=smk-{rule}-{wildcards}
    --account=helikarlab
    --threads={threads}
    --mem={resources.mem_mb}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.runtime}
    --parsable

# Job submittion
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 100

# Other settings
printshellcmds: True
scheduler: greedy


# Do not change these settings. This pipeline will fail to execute if they are changed
use-conda: True
conda-frontend: mamba
