# This file configures various settings for snakemake to execute jobs to a SLURM cluster.
# FROM: https://github.com/jdblischak/smk-simple-slurm

executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule}/{resources.tissue_name} &&
  sbatch
    --job-name=smk-{rule}-{wildcards}
    --account=helikarlab
    --cpus-per-task={threads}
    --output=logs/{rule}/{resources.tissue_name}/{rule}-{wildcards}.out
    --mem={resources.mem_mb}
    --time={resources.runtime}
    --parsable

# Define tissue name
default-resources:
  - mem_mb=2048

# Job submittion
cores: 16  # max cores used in snakefile
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 50
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 5
latency-wait: 60
jobs: 100

# Other settings
printshellcmds: True
rerun-incomplete: True

# Do not change these settings. This pipeline will fail to execute or execute extremely slowly if they are changed
use-conda: True
conda-frontend: mamba
